### ISSUE TITLE
TypeError: an integer is required

### ISSUE THREAD

**Issue by ootjersb** [XtheOne/Inverter-Data-Logger#13]
I am trying to run the LiveStats.py script (running Python 3) and it returns the following

2018-01-11 14:24:21,781 DEBUG Importing output plugin ConsoleOutput
2018-01-11 14:24:21,783 INFO Connecting to logger with IP: 10.0.0.35 and SN 604087423
2018-01-11 14:24:21,787 INFO connecting to 10.0.0.35 port 8899
Traceback (most recent call last):
  File "LiveStats.py", line 17, in <module>
    inverter_exporter.run()
  File "C:\Git\Inverter-Data-Logger\InverterExport.py", line 116, in run
    data = InverterLib.createV4RequestFrame(int(sn))
  File "C:\Git\Inverter-Data-Logger\InverterLib.py", line 33, in createV4Request
Frame
    tar = bytearray([binascii.hexlify(serial_hex[i:i + 2]) for i in reversed(ran
ge(0, len(serial_hex), 2))])
**TypeError: an integer is required**

**Comment by XtheOne** [comment]
Try the python 2&3 branch (still not ready but works partially).
