### ISSUE TITLE
Cant get it installed

### ISSUE THREAD

**Issue by hlubach** [XtheOne/Inverter-Data-Logger#38]
Copied file to rpi  but when i try to run it i've got this

LibreELEC:~/Omnik # python LiveStats.py
Traceback (most recent call last):
  File "LiveStats.py", line 7, in <module>
    import InverterExport
  File "/storage/Omnik/InverterExport.py", line 18, in <module>
    from PluginLoader import Plugin
  File "/storage/Omnik/PluginLoader.py", line 3, in <module>
    from six import add_metaclass
ImportError: No module named six

**Comment by cz-lucas** [comment]
First you need to install python-pip. Then install type in:
`pip install six`
