### ISSUE TITLE
 solis 3 phase and datalogger EN2-8M

### ISSUE THREAD

**Issue by atryda22** [XtheOne/Inverter-Data-Logger#41]
Hello

I have the Solis 3p5k-4g (it is 3 phase) inverter.
Equipped with datalogger EN2-8M.
I configured your project and tested.
Sometimes I got this message:
2021-03-21 09:35:33,138 DEBUG Importing output plugin ConsoleOutput
2021-03-21 09:35:33,139 INFO Connecting to logger with IP: 192.168.1.8 and SN 722549719
2021-03-21 09:35:33,139 INFO connecting to 192.168.1.8 port 8899
2021-03-21 09:35:33,169 DEBUG RAW sent Packet (len=16): 68:02:41:b1:d7:3b:11:2b:d7:3b:11:2b:01:00:91:16  hA;+;+
2021-03-21 09:35:53,190 ERROR Timeout connecting to logger with IP: 192.168.1.8 and SN 722549719, trying next logger.

But sometimes I got some replay:
2021-03-21 09:34:44,668 DEBUG Importing output plugin ConsoleOutput
2021-03-21 09:34:44,669 INFO Connecting to logger with IP: 192.168.1.8 and SN 722549719
2021-03-21 09:34:44,672 INFO connecting to 192.168.1.8 port 8899
2021-03-21 09:34:44,767 DEBUG RAW sent Packet (len=16): 68:02:41:b1:d7:3b:11:2b:d7:3b:11:2b:01:00:91:16  hA;+;+
2021-03-21 09:35:01,771 DEBUG RAW received Packet (len=14): a5:01:00:10:47:d9:8a:d7:3b:11:2b:00:09:15  G;+
2021-03-21 09:35:01,772 DEBUG DATA len=1:
2021-03-21 09:35:01,773 INFO Inverter ID:
Traceback (most recent call last):
  File "LiveStats.py", line 17, in <module>
    inverter_exporter.run()
  File "/home/atryda22/Inverter-Data-Logger/InverterExport.py", line 157, in run
    self.logger.info("RUN State: {0}".format(msg.run_state))
  File "/home/atryda22/Inverter-Data-Logger/InverterMsg.py", line 138, in run_state
    return int(self.__get_short(offset[14], 1))
  File "/home/atryda22/Inverter-Data-Logger/InverterMsg.py", line 78, in __get_short
    num = struct.unpack('!H', self.raw_msg[begin:begin + 2])[0]

Is it because of bad configuration or my DL is not supported?

regards
atryda

**Comment by RPJacobs** [comment]
Look like you're inverter is version 5 (a5 - received Packet )
